version: "3"
services: 
    app:
        container_name: bookstore_api_test
        build: 
            dockerfile: Dockerfile
            context: .
        volumes:
            - .:/app
        ports: 
            - "3000:3000"
        